# Generated by Django 4.0.5 on 2022-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10)),
                ('bevanda', models.CharField(max_length=30)),
                ('prezzo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Colonna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCol', models.IntegerField()),
                ('bibita', models.CharField(max_length=30)),
                ('numeroLatt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tessera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=5)),
                ('credito', models.FloatField()),
            ],
        ),
    ]
